// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using NexusForever.Shared.Database.Auth.Model;

namespace NexusForever.Shared.Database.Auth.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20181024212728_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NexusForever.Shared.Database.Auth.Model.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createTime")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email")
                        .HasColumnType("varchar(128)")
                        .HasDefaultValueSql("''")
                        .HasMaxLength(128);

                    b.Property<string>("GameToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gameToken")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''")
                        .HasMaxLength(32);

                    b.Property<string>("S")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("s")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''")
                        .HasMaxLength(32);

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sessionKey")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''")
                        .HasMaxLength(32);

                    b.Property<string>("V")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("v")
                        .HasColumnType("varchar(512)")
                        .HasDefaultValueSql("''")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("email");

                    b.HasIndex("GameToken")
                        .HasName("gameToken");

                    b.HasIndex("SessionKey")
                        .HasName("sessionKey");

                    b.ToTable("account");
                });

            modelBuilder.Entity("NexusForever.Shared.Database.Auth.Model.Server", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("host")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValueSql("'127.0.0.1'")
                        .HasMaxLength(64);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValueSql("'NexusForever'")
                        .HasMaxLength(64);

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("port")
                        .HasDefaultValueSql("'24000'");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.ToTable("server");
                });
#pragma warning restore 612, 618
        }
    }
}
