// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Shared.Database.Auth.Model;

namespace NexusForever.Migrations.MySql.Auth.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NexusForever.Shared.Database.Auth.Model.Account", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createTime")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email")
                        .HasColumnType("varchar(128)")
                        .HasDefaultValueSql("''");

                    b.Property<string>("GameToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gameToken")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''");

                    b.Property<string>("S")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("s")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sessionKey")
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("''");

                    b.Property<string>("V")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("v")
                        .HasColumnType("varchar(512)")
                        .HasDefaultValueSql("''");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("email");

                    b.HasIndex("GameToken")
                        .HasName("gameToken");

                    b.HasIndex("SessionKey")
                        .HasName("sessionKey");

                    b.ToTable("account");
                });

            modelBuilder.Entity("NexusForever.Shared.Database.Auth.Model.Server", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("host")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValueSql("'127.0.0.1'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)")
                        .HasDefaultValueSql("'NexusForever'");

                    b.Property<ushort>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("port")
                        .HasDefaultValueSql("'24000'");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.ToTable("server");
                });
#pragma warning restore 612, 618
        }
    }
}
