// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NexusForever.WorldServer.Database.Character.Model.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20181024224409_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.Character", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("accountId")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte>("Class")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("class")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createTime")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("''");

                    b.Property<byte>("Race")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("race")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte>("Sex")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sex")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasName("accountId");

                    b.ToTable("character");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.CharacterAppearance", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("slot")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("displayId")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id", "Slot");

                    b.ToTable("character_appearance");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.CharacterCustomisation", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Label")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("label")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("value")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id", "Label");

                    b.ToTable("character_customisation");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.Item", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("BagIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bagIndex")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Charges")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("charges")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Durability")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("durability")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("ExpirationTimeLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("expirationTimeLeft")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("itemId")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Location")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("location")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("ownerId")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("StackCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("stackCount")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasName("FK__item_ownerId__character_id");

                    b.ToTable("item");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.CharacterAppearance", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.Character.Model.Character", "IdNavigation")
                        .WithMany("CharacterAppearance")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__character_appearance_id__character_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.CharacterCustomisation", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.Character.Model.Character", "IdNavigation")
                        .WithMany("CharacterCustomisation")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__character_customisation_id__character_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.Character.Model.Item", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.Character.Model.Character", "Owner")
                        .WithMany("Item")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK__item_ownerId__character_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
