// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NexusForever.WorldServer.Database.World.Model.Migrations
{
    [DbContext(typeof(WorldContext))]
    [Migration("20181024224327_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Creature")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("creature")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("DisplayInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("displayInfo")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Faction1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("faction1")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Faction2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("faction2")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("OutfitInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("outfitInfo")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Rx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rx")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Ry")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ry")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Rz")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rz")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("World")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("world")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("x")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("y")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("z")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.ToTable("entity");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("BuyPriceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("buyPriceMultiplier")
                        .HasDefaultValueSql("'1'");

                    b.Property<float>("SellPriceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sellPriceMultiplier")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("Id");

                    b.ToTable("entity_vendor");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendorCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("index")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("LocalisedTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("localisedTextId")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id", "Index");

                    b.ToTable("entity_vendor_category");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendorItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("index")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("CategoryIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("categoryIndex")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("itemId")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id", "Index");

                    b.ToTable("entity_vendor_item");
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendor", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.World.Model.Entity", "IdNavigation")
                        .WithOne("EntityVendor")
                        .HasForeignKey("NexusForever.WorldServer.Database.World.Model.EntityVendor", "Id")
                        .HasConstraintName("FK__entity_vendor_id__entity_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendorCategory", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.World.Model.Entity", "IdNavigation")
                        .WithMany("EntityVendorCategory")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__entity_vendor_category_id__entity_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexusForever.WorldServer.Database.World.Model.EntityVendorItem", b =>
                {
                    b.HasOne("NexusForever.WorldServer.Database.World.Model.Entity", "IdNavigation")
                        .WithMany("EntityVendorItem")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__entity_vendor_item_id__entity_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
